master:
  push:
    - docker:
        image: node:23
      stages:
        - name: install dependencies
          script: yarn install
        - name: build
          script: yarn build
        - name: publish
          script: yarn publish --non-interactive --no-git-tag-version